// src/utils/roboto.js
export const robotoNormal = `
AAEAAAAPAIAAAwBwRkZUTWb5VyEAAAC8AAAAYGNtYXASmVOZAAABBAAAADZnbHlmNlJtSAAAAXgAAAA
IZ2x5ZgAAAAAAAAQAAAAWAABnbHlmbyWcVQAAAQgAAAHRGhlYWQAAA8DAAAAbAAAADZoaGVhBn8FZAA
AASgAAAAkaG10eC3PAAAADvAAAACkYbWF4cAHCAAAAFUgAAAAgbmFtZXQslEYAAARwAAAELLnBvc3Qw
D0QA...
`; // сокращено — на самом деле длинный base64

export const robotoBold = `
AAEAAAAPAIAAAwBwRkZUTSNryxwAAAC8AAAAYGNtYQA9YAGWAAABB... 
`; // тоже длинный base64
